// Generated by ReScript, PLEASE EDIT WITH CARE


var Activity = {};

var Alert = {};

var ArrowDown = {};

var ArrowLeft = {};

var ArrowUp = {};

var Award = {};

var Check = {};

var CheckCircle = {};

var ChevronDown = {};

var ChevronLeft = {};

var ChevronUp = {};

var Circle = {};

var Clock = {};

var Download = {};

var Edit = {};

var ExternalLink = {};

var Help = {};

var Home = {};

var Info = {};

var Layers = {};

var List = {};

var Menu = {};

var Plus = {};

var Repeat = {};

var Settings = {};

var Trash = {};

var UserMinus = {};

var UserPlus = {};

var Users = {};

var X = {};

var More = {};

export {
  Activity ,
  Alert ,
  ArrowDown ,
  ArrowLeft ,
  ArrowUp ,
  Award ,
  Check ,
  CheckCircle ,
  ChevronDown ,
  ChevronLeft ,
  ChevronUp ,
  Circle ,
  Clock ,
  Download ,
  Edit ,
  ExternalLink ,
  Help ,
  Home ,
  Info ,
  Layers ,
  List ,
  Menu ,
  Plus ,
  Repeat ,
  Settings ,
  Trash ,
  UserMinus ,
  UserPlus ,
  Users ,
  X ,
  More ,
}
/* No side effect */
